package model;
// Generated 07-sep-2016 18:36:07 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Produccion generated by hbm2java
 */
public class Produccion  implements java.io.Serializable {


     private Integer id;
     private Date fechaHora;
     private Integer puestoTrabajo;
     private String chasis;
     private Integer modelo;
     private Integer estado;

    public Produccion() {
    }

	
    public Produccion(Date fechaHora) {
        this.fechaHora = fechaHora;
    }
    public Produccion(Date fechaHora, Integer puestoTrabajo, String chasis, Integer modelo, Integer estado) {
       this.fechaHora = fechaHora;
       this.puestoTrabajo = puestoTrabajo;
       this.chasis = chasis;
       this.modelo = modelo;
       this.estado = estado;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getFechaHora() {
        return this.fechaHora;
    }
    
    public void setFechaHora(Date fechaHora) {
        this.fechaHora = fechaHora;
    }
    public Integer getPuestoTrabajo() {
        return this.puestoTrabajo;
    }
    
    public void setPuestoTrabajo(Integer puestoTrabajo) {
        this.puestoTrabajo = puestoTrabajo;
    }
    public String getChasis() {
        return this.chasis;
    }
    
    public void setChasis(String chasis) {
        this.chasis = chasis;
    }
    public Integer getModelo() {
        return this.modelo;
    }
    
    public void setModelo(Integer modelo) {
        this.modelo = modelo;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }




}


